### ISSUE TITLE
Examples not running

### ISSUE THREAD

**Issue by p3jawors** [modelon-community/PyFMI#124]
Hello,

I have installed the dependencies and installed the repository pointing it to the FMILibrary install. I am on Ubuntu 20.04 and using an anaconda environment with Python==3.6.13 with these packages
```
Package            Version
------------------ ---------
Assimulo           3.2.5
attrs              21.2.0
certifi            2021.5.30
cffi               1.11.5
chardet            3.0.4
charset-normalizer 2.0.6
cryptography       2.8
cycler             0.10.0
Cython             0.29.14
dask               2021.3.0
FMPy               0.3.1
idna               3.2
kiwisolver         1.3.1
lark-parser        0.12.0
lxml               4.6.3
matplotlib         3.3.4
msgpack            1.0.2
nose               1.3.7
numpy              1.19.5
Pillow             8.3.2
pip                21.0.1
pycparser          2.20
PyFMI              2.5
pylab-sdk          1.3.2
pyOpenSSL          19.1.0
pyparsing          2.4.7
PySocks            1.7.1
python-dateutil    2.8.2
pytz               2021.1
PyYAML             5.4.1
requests           2.26.0
scipy              1.5.4
setuptools         58.0.4
six                1.16.0
urllib3            1.26.6
wheel              0.37.0
```

I am running into an issue when I try to access any results as is done in your examples. In fact I also get the same error thrown trying to run the examples.
`pyfmi.common.io.VariableNotFoundError`

When I try to run the `fmi_bouncing_ball.py` example it throws this... 
```
Traceback (most recent call last):
  File "/home/pjaworsk/miniconda3/envs/fmi/lib/python3.6/site-packages/pyfmi/common/io.py", line 137, in get_variable_index
    return self.name_lookup[name]
KeyError: 'h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fmi_bouncing_ball.py", line 68, in <module>
    run_demo()
  File "fmi_bouncing_ball.py", line 43, in run_demo
    h_res = res['h']
  File "/home/pjaworsk/miniconda3/envs/fmi/lib/python3.6/site-packages/pyfmi/common/algorithm_drivers.py", line 178, in __getitem__
    val_x = self.result_data.get_variable_data(key).x
  File "/home/pjaworsk/miniconda3/envs/fmi/lib/python3.6/site-packages/pyfmi/common/io.py", line 1162, in get_variable_data
    varInd  = self.get_variable_index(name)
  File "/home/pjaworsk/miniconda3/envs/fmi/lib/python3.6/site-packages/pyfmi/common/io.py", line 153, in get_variable_index
    name + " in data file.")
pyfmi.common.io.VariableNotFoundError: Cannot find variable h in data file.
```

Is there something I may have done incorrectly with my install? I have come across [this post](https://stackoverflow.com/questions/58219336/cant-retrieve-the-results-back-from-jmodelica-to-python,), but that seems to be when compiling an fmu. In my scenario I have the `.fmu` zip and am trying to open it and run a simulation while reading outputs and providing inputs.

**Comment by p3jawors** [comment]
It looks like this is a problem with the pip version of pyfmi, using a git clone I can run the examples.
