### ISSUE TITLE
Insallation fails with ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by TimotheusT** [modelon-community/PyFMI#218]
A clean install results in the following error with python 3.12:

```
D:\projects\Python\TestWorkspace> pip install pyfmi
Collecting pyfmi
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "d:\projects\Python\TestWorkspace\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "d:\projects\Python\TestWorkspace\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "d:\projects\Python\TestWorkspace\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\XXXXXXX\AppData\Local\Temp\pip-build-env-xki3nlv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel   
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\XXXXXXX\AppData\Local\Temp\pip-build-env-xki3nlv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\XXXXXXX\AppData\Local\Temp\pip-build-env-xki3nlv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\XXXXXXX\AppData\Local\Temp\pip-build-env-xki3nlv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 26, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Installing numpy in the same venv does not help

**Comment by PeterMeisrimelModelon** [comment]
Hi,

building PyFMI with Python >= 3.12 is currently not possible since distutils was removed with Python 3.12. See also https://github.com/modelon-community/PyFMI/issues/203. It is on our roadmap to fix this. Until then, the only way is to use at most Python 3.11.x

**Comment by IkerLandaa** [comment]
Hi all,

I am also struggling to build PyFMI with Python, I have tried with versions 3.10, 3.11 and 3.12 with same error as described by @TimotheusT. Any help will be appreciated :)

**Comment by modelonrobinandersson** [comment]
Hi @IkerLandaa, 3.12 is not yet supported (working on it). But for 3.10 or 3.11 I suggest that you install it via conda-forge as it is the easiest today, see: https://github.com/modelon-community/PyFMI?tab=readme-ov-file#installation-using-conda.

You can also build PyFMI from source but then you also need to build FMI Library and Assimulo needs to be installed before since it is a build dependency.
