### ISSUE TITLE
String input / output support

### ISSUE THREAD

**Issue by YanceyYq** [modelon-community/PyFMI#256]
does PyFMI support input / output String variables?

When I load values.fmu, I encountered the following error.
Traceback (most recent call last):
  File "/home/yancey/Desktop/FMU/Fmu/Test/win1.0/maketest/test27/dist/fmu20/me/fmiMe_inc.py", line 45, in <module>
    model_sub_2 = Dummy_FMUModelME2([], os.path.join(me2_xml_path, "values.fmu"), _connect_dll=False)
  File "src/pyfmi/tests/test_util.pyx", line 333, in pyfmi.tests.test_util.Dummy_FMUModelME2.__init__
  File "src/pyfmi/tests/test_util.pyx", line 348, in pyfmi.tests.test_util.Dummy_FMUModelME2.reset
ValueError: could not convert string to float: b'QTronic'

**Comment by PeterMeisrimelModelon** [comment]
Hi YanceyYq,

yes, these are supported. 

1. The Dummy_FMU* class are designed for unit tests only. Use the FMUModel* class from pyfmi.fmi.
2. Since strings do not have numerical values, they are not stored as result trajectories by default, but you can obtain them via fmu.get(...). This works for string outputs without any extra modifications.
3. Discrete inputs require some extra thought, inputs in PyFMI are primarily designed for continuous inputs. For discrete inputs, you likely want to invoke an event in the FMU such that the discrete change is applied, since discrete values may only change at events. 

The following principle code should work for string inputs:
```
fmu = load_fmu(...)

tt = [0, 1, 2, 3] # time-points for string inputs
uu = ['a', 'b', 'c'] # string values between tt points


fmu.set(<string_variable>, u[0])
fmu.simulate(tt[0], tt[1])

# ...

fmu.set(<string_variable>, u[1])
fmu.event_update()
fmu.simulate(tt[1], tt[2], options = {"initialize": False})

# ...

fmu.set(<string_variable>, u[2])
fmu.event_update()
fmu.simulate(tt[2], tt[3], options = {"initialize": False})

# ...
```

/Peter

**Comment by YanceyYq** [comment]
In the test_fmi_coupled.py file, if  loading an FMU file using FMUModelME2 but unable to find the operation to execute the simulation,  can you guide me on how to proceed?

**Comment by PeterMeisrimelModelon** [comment]
I am not sure I understand the question, the principle format there is

```
model_1 = FMUModelME2(...)
model_2 = FMUModelME2(...)

# ...

models = [("First", model_1), ("Second", model_2)]
connections = ...

coupled = CoupledFMUModelME2(models, connections=connections)

res = coupled.simulate(options=opts)

```

Please provide some code & context if you experiencing any issues with this.

**Comment by YanceyYq** [comment]
I found what I was looking for in your answer. Thank you for your help.

**Comment by YanceyYq** [comment]
I'm sorry, but I've found another issue.
When execute “model_sub_1 = FMUModelME2(os.path.join(me2_xml_path, "inc.fmu"), _connect_dll=False)”, it generates an error message that says "Segmentation fault (core dumped)"，I have confirmed that the inc.fmu file exists in the directory specified by me2_xml_path.

**Comment by YanceyYq** [comment]
Please disregard the previous question.
"Segmentation fault (core dumped)" occurs when results = coupled.simulate(options=opts) is executed.
My execution steps are:
model_sub_1 = FMUModelME2(os.path.join(me2_xml_path, "./inc.fmu"), _connect_dll=False)
model_sub_2 = FMUModelME2(os.path.join(me2_xml_path, "./values.fmu"), _connect_dll=False)
models = [("First", model_sub_1), ("Second", model_sub_2)]
connections = [(model_sub_1, "counter", model_sub_2, "int_in")]
coupled = CoupledFMUModelME2(models, connections=connections)
opts = {"CVode_options": {"rtol": 1e-6, "atol": 1e-6}, "ncp": 0}
results = coupled.simulate(options=opts)

**Comment by PeterMeisrimelModelon** [comment]
Drop the `_connect_dll = False`. This is a "developer option" that we use for testing. It allows us to load the FMU without requiring the binaries. This is used to test interaction with the modelDescription.xml.

Anything that then requires the binaries will fail, but that is expected.

**Comment by YanceyYq** [comment]
Drop the _connect_dll = False. The following error appears:
[ERROR][rank 0][/home/conda/feedstock_root/build_artifacts/sundials-split_1714675156483/work/sundials/src/cvodes/cvodes.c:2998][CVode] The right-hand side routine failed at the first call.
Traceback (most recent call last):
  File "/home/yancey/Desktop/FMU/Fmu/Test/win1.0/maketest/test30/dist/fmu20/me/fmiMe_inc2.py", line 62, in <module>
    results = coupled.simulate(options=opts)
  File "src/pyfmi/fmi_coupled.pyx", line 2416, in pyfmi.fmi_coupled.CoupledFMUModelME2.simulate
  File "src/pyfmi/fmi_coupled.pyx", line 139, in pyfmi.fmi_coupled.CoupledModelBase._exec_simulate_algorithm
  File "src/pyfmi/fmi_coupled.pyx", line 134, in pyfmi.fmi_coupled.CoupledModelBase._exec_simulate_algorithm
  File "/home/yancey/miniconda3/envs/Fmu/lib/python3.9/site-packages/pyfmi/fmi_algorithm_drivers.py", line 716, in solve
    self.simulator.simulate(self.final_time, self.ncp)
  File "assimulo/ode.pyx", line 192, in assimulo.ode.ODE.simulate
  File "assimulo/ode.pyx", line 315, in assimulo.ode.ODE.simulate
  File "assimulo/explicit_ode.pyx", line 137, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/explicit_ode.pyx", line 223, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/solvers/sundials.pyx", line 2103, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 2136, in assimulo.solvers.sundials.CVode.integrate
assimulo.solvers.sundials.CVodeError: 'The right-hand side function failed at the first call. At time 0.000000.'

**Comment by PeterMeisrimelModelon** [comment]
This would indicate that your model failed to evaluate with the first attempt to evaluate it, there are no real fallbacks to this. I do not see any obvious flaws in the code you attached earlier, this might very well be a problem of the the model.
I'd recommend the following:

1. Check that your FMUs simulate in isolation, before trying to couple them.
2. Increase log level and check the logs. There should hopefully be more information in there about what is going wrong in your model, when trying to evaluate this.

/Peter

**Comment by YanceyYq** [comment]
FMpy can be used to simulate each Fmu individually.

**Comment by PeterMeisrimelModelon** [comment]
... and what do the logs say?

**Comment by YanceyYq** [comment]
The Fmu file used is an example file from the FMUSDK.Increase log level and check the logs
Show log：
FMIL: module = Model, log level = 2: [logError][FMU status:Error] fmi2SetInteger: Illegal call sequence.
FMIL: module = Model, log level = 2: [logError][FMU status:Error] fmi2Terminate: Illegal call sequence.

**Comment by YanceyYq** [comment]
This is my implementation, do you have any other ideas to offer?
```
model_sub_1 = FMUModelME2(os.path.join(me2_xml_path, "./inc.fmu"))
model_sub_2 = FMUModelME2(os.path.join(me2_xml_path, "./values.fmu"))
models = [("First", model_sub_1), ("Second", model_sub_2)]
connections = [(model_sub_1, "counter", model_sub_2, "int_in")]
coupled = CoupledFMUModelME2(models, connections=connections)
opts = {"CVode_options": {"rtol": 1e-6, "atol": 1e-6}, "ncp": 0}
results = coupled.simulate(options=opts)
y1_values = results['First.counter']
y3_values = results['Second.int_in']
y2_values = results['Second.int_out']
num_time_steps = len(y1_values) 
times = np.arange(num_time_steps)

```
This is my implementation, do you have any other ideas to offer?

**Comment by PeterMeisrimelModelon** [comment]
Can you try to increase the log level and check the log? I.e., `FMUModelME2(..., log_level = 7)`

/Peter

**Comment by YanceyYq** [comment]
inc_log.txt
```
FMIL: module = FMILIB, log level = 5: Allocating FMIL context
FMIL: module = FMILIB, log level = 5: Detecting FMI standard version
FMIL: module = FMIZIP, log level = 5: Unpacking FMU into /tmp/yancey/JModelica.org/jm_tmpln_8gvv2
FMIL: module = FMIXML, log level = 5: Parsing XML to detect FMI standard version
FMIL: module = FMIXML, log level = 5: XML specifies FMI 2.0
FMIL: module = FMILIB, log level = 4: XML specifies FMI standard version 2.0
FMIL: module = FMILIB, log level = 5: Parsing model description XML
FMIL: module = FMI2XML, log level = 5: Parsing XML element fmiModelDescription
FMIL: module = FMI2XML, log level = 5: Parsing XML element ModelExchange
FMIL: module = FMI2XML, log level = 5: Parsing XML element LogCategories
FMIL: module = FMI2XML, log level = 5: Parsing XML element ModelVariables
FMIL: module = FMI2XML, log level = 5: Parsing XML element ModelStructure
FMIL: module = FMI2XML, log level = 5: Parsing XML element Outputs
FMIL: module = FMILIB, log level = 5: Parsing finished successfully
FMIL: module = FMILIB, log level = 4: Loading 'linux64' binary with 'default' platform types
FMIL: module = FMICAPI, log level = 5: Loaded FMU binary from /tmp/yancey/JModelica.org/jm_tmpln_8gvv2/binaries/linux64/inc.so
FMIL: module = FMICAPI, log level = 5: Loading functions for the model exchange interface
FMIL: module = FMILIB, log level = 5: Successfully loaded all the interface functions
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2Instantiate: GUID={8c4e810f-3df3-4a00-8276-176fa3c9f008}
FMIL: module = FMI2XML, log level = 3: fmi2_xml_get_default_experiment_start: returning default value, since no attribute was defined in modelDescription
FMIL: module = FMI2XML, log level = 3: fmi2_xml_get_default_experiment_start: returning default value, since no attribute was defined in modelDescription
FMIL: module = FMI2XML, log level = 3: fmi2_xml_get_default_experiment_stop: returning default value, since no attribute was defined in modelDescription
FMIL: module = FMI2XML, log level = 3: fmi2_xml_get_default_experiment_stop: returning default value, since no attribute was defined in modelDescription
FMIL: module = FMICAPI, log level = 5: Calling fmi2SetupExperiment
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetupExperiment: toleranceDefined=1 tolerance=1e-06
FMIL: module = FMICAPI, log level = 5: Calling fmi2EnterInitializationMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2EnterInitializationMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetInteger: counter = 1
FMIL: module = FMICAPI, log level = 5: Calling fmi2ExitInitializationMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2ExitInitializationMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetInteger: counter = 1
FMIL: module = FMICAPI, log level = 5: Calling fmi2NewDiscreteStates
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2NewDiscreteStates
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetInteger: counter = 1
FMIL: module = FMICAPI, log level = 5: Calling fmi2EnterContinuousTimeMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2EnterContinuousTimeMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetTime: time=0
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetInteger: counter = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetTime: time=0
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetInteger: counter = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2Terminate
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2FreeInstance
FMIL: module = FMILIB, log level = 5: Releasing FMU CAPI interface
FMIL: module = FMICAPI, log level = 5: Successfully unloaded FMU binary
FMIL: module = FMILIB, log level = 5: Releasing allocated library resources
FMIL: module = JMPRT, log level = 5: Removing /tmp/yancey/JModelica.org/jm_tmpln_8gvv2

```
values_log.txt

```
FMIL: module = FMILIB, log level = 5: Allocating FMIL context
FMIL: module = FMILIB, log level = 5: Detecting FMI standard version
FMIL: module = FMIZIP, log level = 5: Unpacking FMU into /tmp/yancey/JModelica.org/jm_tmpjyqe36oq
FMIL: module = FMIXML, log level = 5: Parsing XML to detect FMI standard version
FMIL: module = FMIXML, log level = 5: XML specifies FMI 2.0
FMIL: module = FMILIB, log level = 4: XML specifies FMI standard version 2.0
FMIL: module = FMILIB, log level = 5: Parsing model description XML
FMIL: module = FMI2XML, log level = 5: Parsing XML element fmiModelDescription
FMIL: module = FMI2XML, log level = 5: Parsing XML element ModelExchange
FMIL: module = FMI2XML, log level = 5: Parsing XML element LogCategories
FMIL: module = FMI2XML, log level = 5: Parsing XML element ModelVariables
FMIL: module = FMI2XML, log level = 5: Building alias index
FMIL: module = FMI2XML, log level = 5: Parsing XML element ModelStructure
FMIL: module = FMI2XML, log level = 5: Parsing XML element Outputs
FMIL: module = FMI2XML, log level = 5: Parsing XML element Derivatives
FMIL: module = FMI2XML, log level = 5: Parsing XML element InitialUnknowns
FMIL: module = FMILIB, log level = 5: Parsing finished successfully
FMIL: module = FMILIB, log level = 4: Loading 'linux64' binary with 'default' platform types
FMIL: module = FMICAPI, log level = 5: Loaded FMU binary from /tmp/yancey/JModelica.org/jm_tmpjyqe36oq/binaries/linux64/values.so
FMIL: module = FMICAPI, log level = 5: Loading functions for the model exchange interface
FMIL: module = FMILIB, log level = 5: Successfully loaded all the interface functions
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetString: nvr = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetString: string_in = 'QTronic'
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetString: nvr = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetString: string_out = 'jan'
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2Instantiate: GUID={8c4e810f-3df3-4a00-8276-176fa3c9f004}
FMIL: module = FMI2XML, log level = 3: fmi2_xml_get_default_experiment_start: returning default value, since no attribute was defined in modelDescription
FMIL: module = FMI2XML, log level = 3: fmi2_xml_get_default_experiment_stop: returning default value, since no attribute was defined in modelDescription
FMIL: module = FMICAPI, log level = 5: Calling fmi2SetupExperiment
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetupExperiment: toleranceDefined=1 tolerance=1e-06
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetInteger: nvr = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetInteger: int_in = 1
FMIL: module = FMICAPI, log level = 5: Calling fmi2EnterInitializationMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2EnterInitializationMode
FMIL: module = FMICAPI, log level = 5: Calling fmi2ExitInitializationMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2ExitInitializationMode
FMIL: module = FMICAPI, log level = 5: Calling fmi2NewDiscreteStates
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2NewDiscreteStates
FMIL: module = FMICAPI, log level = 5: Calling fmi2EnterContinuousTimeMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2EnterContinuousTimeMode
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetTime: time=0
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetContinuousStates: x = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetContinuousStates: x = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetReal: x = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetReal: der(x) = -1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetInteger: int_in = 1
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetInteger: int_out = 0
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetBoolean: bool_in = true
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2GetBoolean: bool_out = false
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetTime: time=0
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2SetContinuousStates: x=1
FMIL: module = Model, log level = 2: [logError][FMU status:Error] fmi2SetInteger: Illegal call sequence.
FMIL: module = Model, log level = 2: [logError][FMU status:Error] fmi2Terminate: Illegal call sequence.
FMIL: module = Model, log level = 4: [logFmiCall][FMU status:OK] fmi2FreeInstance
FMIL: module = FMILIB, log level = 5: Releasing FMU CAPI interface
FMIL: module = FMICAPI, log level = 5: Successfully unloaded FMU binary
FMIL: module = FMILIB, log level = 5: Releasing allocated library resources
FMIL: module = JMPRT, log level = 5: Removing /tmp/yancey/JModelica.org/jm_tmpjyqe36oq

```
The log looks fine.Is my simulation code correct?

**Comment by PeterMeisrimelModelon** [comment]
The issue here is in the 2nd log:

`FMIL: module = Model, log level = 2: [logError][FMU status:Error] fmi2SetInteger: Illegal call sequence.`

This occurs during continuous time mode. Integers are discrete by nature and setting them during continuous time-mode is not permitted, hence the error leading to termination.

I suspect this comes from your connections:  `[(model_sub_1, "counter", model_sub_2, "int_in")]`, where `int_in` is presumably an integer.

See https://github.com/modelon-community/PyFMI/issues/256#issuecomment-2285709668 for the issue with exchanging discrete values between models.

/Peter

**Comment by YanceyYq** [comment]
```
FMIL: module = Model, log level = 2: [logError][FMU status:Error] fmi2SetInteger: Illegal call sequence.
FMIL: module = Model, log level = 2: [logError][FMU status:Error] fmi2Terminate: Illegal call sequence.
```
 these two error messages.Does this mean there is a problem with the fmu file?

**Comment by PeterMeisrimelModelon** [comment]
The `module = Model` indicates that this log message is generated by the model. However, you are using the Models in a way that is not permissible with the FMI standard.

**Comment by PeterMeisrimelModelon** [comment]
Connection end-points must be continuous inputs. Integers are not continuous.

**Comment by YanceyYq** [comment]
```
  <ScalarVariable name="x" valueReference="0" description="used as continuous state"
                  causality="local" variability="continuous" initial="exact">
    <Real start="1"/>
  </ScalarVariable>
  <ScalarVariable name="der(x)" valueReference="1" description="time derivative of x"
                  causality="local" variability="continuous" initial="calculated">
    <Real derivative="1"/>
  </ScalarVariable>
  <ScalarVariable name="int_in" valueReference="0" description="integer input"
                  causality="input" variability="discrete">
    <Integer start="2"/>
  </ScalarVariable>
  <ScalarVariable name="int_out" valueReference="1" description="index in string array 'month'"
                  causality="output" variability="discrete" initial="exact">
    <Integer start="0"/>
  </ScalarVariable>
  <ScalarVariable name="bool_in" valueReference="0" description="boolean input"
                  causality="input" variability="discrete">
    <Boolean start="true"/>
  </ScalarVariable>
  <ScalarVariable name="bool_out" valueReference="1" description="boolean output"
                  causality="output" variability="discrete" initial="exact">
    <Boolean start="false"/>
  </ScalarVariable>
  <ScalarVariable name="string_in" valueReference="0" description="string input"
                  causality="input" variability="discrete">
    <String start="QTronic"/>
  </ScalarVariable>
  <ScalarVariable name="string_out" valueReference="1" description="the string month[int_out]"
                  causality="output" variability="discrete" initial="exact">
    <String start="jan"/>
  </ScalarVariable>
```

Among these parameters, are there any that can be Connection end-points ?

**Comment by PeterMeisrimelModelon** [comment]
Well, are any of these continuous inputs?

**Comment by YanceyYq** [comment]
How can I judge whether a parameter is continuous inputs?

**Comment by PeterMeisrimelModelon** [comment]
Does any Variable have both `causality="input"` and `variability="continuous"`?

Also, this is no longer a PyFMI specific question, but a general question on how to use FMI and/or how you want to design your model(s) and their coupling. I'd be closing the issue due to that.
