### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by YanceyYq** [modelon-community/PyFMI#263]
hello,
```
Traceback (most recent call last):
  File "F:\LHFZ\work\fMIKit\sim\fmipp\TestController\Test\Tese.py", line 21, in <module>
    master = Master(models, connections)
  File "src\\pyfmi\\master.pyx", line 469, in pyfmi.master.Master.__init__
  File "src\\pyfmi\\master.pyx", line 739, in pyfmi.master.Master.check_algebraic_loops
KeyError: 'Pheat'
```
For this error, from which aspects should I look for the cause?

**Comment by modelonrobinandersson** [comment]
Hi @YanceyYq, based on where it fails it looks like an you have a dependency between an output and an input, but there is a local output named "Pheat" that is not mapped to any specific input.
Are you able to share the output from the method `get_output_dependencies()` that is callable on your loaded FMUs?

**Comment by YanceyYq** [comment]
run
```
model_sub1 = FMUModelCS2(fmu_path1, log_level=7)
dep1 = model_sub1.get_output_dependencies()
print("Output dependencies1:", dep1)
```
show
```
Output dependencies1: (OrderedDict(), OrderedDict())
```
but The causality property of 'Pheat' is 'output'.
```
	<ScalarVariable name="Pheat" valueReference="1001" variability="continuous" causality="output" >
			<Real/>
		</ScalarVariable>
```

**Comment by modelonrobinandersson** [comment]
HI @YanceyYq, due to the lack of information in this issue. Can you close this one and open a new one following the template in the bug reporter? Thanks in advance.

**Comment by modelonrobinandersson** [comment]
Closing due to inactivity
