### ISSUE TITLE
log position 

### ISSUE THREAD

**Issue by YanceyYq** [modelon-community/PyFMI#266]
script:
```
model_sub1 = FMUModelCS2(fmu_path1, log_level=7)
model_sub2 = FMUModelCS2(fmu_path2, log_level=7)
models = [model_sub1, model_sub2]
connections = [(model_sub1, out_par, model_sub2, in_par)]
master = Master(models, connections)
opts = master.simulate_options()
opts["step_size"] = 1.0
opts["logging"] = True
res = master.simulate(options=opts, final_time=total_duration)
```
error:
```
 res = master.simulate(options=opts, final_time=total_duration)
Elapsed initialization time: 2.6243388 seconds.
Traceback (most recent call last):
  File "F:\LHFZ\work\Qtfiles\Testtestcon.py", line 30, in <module>
    res = master.simulate(options=opts, final_time=total_duration)
  File "src\\pyfmi\\master.pyx", line 1511, in pyfmi.master.Master.simulate
  File "src\\pyfmi\\master.pyx", line 1311, in pyfmi.master.Master.jacobi_algorithm
  File "src\\pyfmi\\master.pyx", line 55, in pyfmi.master.perform_do_step
  File "src\\pyfmi\\master.pyx", line 72, in pyfmi.master.perform_do_step_serial
pyfmi.fmi.FMUException: The step failed for model SimpleController at time 0.000000. See the log for more information. Return flag 2.
```
I didn't find the location of the log that records detailed information. Where is its location usually?

**Comment by PeterMeisrimelModelon** [comment]
`FMUModelCS2` has the optional argument `log_file_name` (`default = ""`; current location; where your Python script is located) that you can use to specify name and location of the `.txt` log.

/Peter

**Comment by YanceyYq** [comment]
Thank you for your help.
