### ISSUE TITLE
[2.8] assimulo/problem.pxd' not found

### ISSUE THREAD

**Issue by jschueller** [modelon-community/PyFMI#55]
pyfmi 2.8 does not build when assimulo is not present, eventhought there seems to be a bool (assimulo_present) checking if assimulo is there or not
```
2020-10-07T14:09:36.1942374Z Compiling src/pyfmi/fmi.pyx because it changed.
2020-10-07T14:09:36.1949781Z [1/1] Cythonizing src/pyfmi/fmi.pyx
2020-10-07T14:09:36.2401045Z /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/work/src/pyfmi/fmi.pxd
2020-10-07T14:09:36.2402996Z   tree = Parsing.p_module(s, pxd, full_module_name)
2020-10-07T14:09:36.5076622Z warning: src/pyfmi/fmil_import.pxd:65:4: 'size_t' redeclared 
2020-10-07T14:09:38.1652417Z warning: src/pyfmi/fmi.pyx:3048:40: Obtaining 'fmi1_string_t' from externally modifiable global Python value
2020-10-07T14:09:40.1078519Z Compiling src/pyfmi/fmi_util.pyx because it changed.
2020-10-07T14:09:40.1085231Z [1/1] Cythonizing src/pyfmi/fmi_util.pyx
2020-10-07T14:09:40.1095281Z /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/work/src/pyfmi/fmi_util.pxd
2020-10-07T14:09:40.1097775Z   tree = Parsing.p_module(s, pxd, full_module_name)
2020-10-07T14:09:40.7184884Z warning: src/pyfmi/fmil_import.pxd:65:4: 'size_t' redeclared 
2020-10-07T14:09:42.5024930Z Compiling src/pyfmi/fmi_extended.pyx because it changed.
2020-10-07T14:09:42.5025962Z [1/1] Cythonizing src/pyfmi/fmi_extended.pyx
2020-10-07T14:09:42.5076236Z /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/work/src/pyfmi/fmi_extended.pyx
2020-10-07T14:09:42.5078337Z   tree = Parsing.p_module(s, pxd, full_module_name)
2020-10-07T14:09:42.9469504Z warning: src/pyfmi/fmil_import.pxd:65:4: 'size_t' redeclared 
2020-10-07T14:09:44.0620502Z Compiling src/pyfmi/fmi_coupled.pyx because it changed.
2020-10-07T14:09:44.0630394Z [1/1] Cythonizing src/pyfmi/fmi_coupled.pyx
2020-10-07T14:09:44.0639249Z /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/work/src/pyfmi/fmi_coupled.pyx
2020-10-07T14:09:44.0640915Z   tree = Parsing.p_module(s, pxd, full_module_name)
2020-10-07T14:09:44.5762210Z warning: src/pyfmi/fmil_import.pxd:65:4: 'size_t' redeclared 
2020-10-07T14:09:46.2072315Z Compiling src/pyfmi/simulation/assimulo_interface.pyx because it changed.
2020-10-07T14:09:46.2074378Z [1/1] Cythonizing src/pyfmi/simulation/assimulo_interface.pyx
2020-10-07T14:09:46.2089781Z /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/work/src/pyfmi/simulation/assimulo_interface.pxd
2020-10-07T14:09:46.2091823Z   tree = Parsing.p_module(s, pxd, full_module_name)
2020-10-07T14:09:46.6414352Z warning: src/pyfmi/fmil_import.pxd:65:4: 'size_t' redeclared 
2020-10-07T14:09:47.0093290Z 
2020-10-07T14:09:47.0094476Z Error compiling Cython file:
2020-10-07T14:09:47.0095767Z ------------------------------------------------------------
2020-10-07T14:09:47.0096218Z ...
2020-10-07T14:09:47.0096576Z     assimulo_present = False
2020-10-07T14:09:47.0096882Z 
2020-10-07T14:09:47.0097228Z if assimulo_present:
2020-10-07T14:09:47.0097649Z     from assimulo.problem import Implicit_Problem
2020-10-07T14:09:47.0098107Z     from assimulo.problem import Explicit_Problem
2020-10-07T14:09:47.0098587Z     from assimulo.problem cimport cExplicit_Problem
2020-10-07T14:09:47.0098962Z    ^
2020-10-07T14:09:47.0099650Z ------------------------------------------------------------
2020-10-07T14:09:47.0100049Z 
2020-10-07T14:09:47.0100793Z src/pyfmi/simulation/assimulo_interface.pxd:35:4: 'assimulo/problem.pxd' not found
2020-10-07T14:09:47.0101262Z 
2020-10-07T14:09:47.0101607Z Error compiling Cython file:
2020-10-07T14:09:47.0102332Z ------------------------------------------------------------
2020-10-07T14:09:47.0102989Z ...
2020-10-07T14:09:47.0103319Z     assimulo_present = False
2020-10-07T14:09:47.0103851Z 
2020-10-07T14:09:47.0104178Z if assimulo_present:
2020-10-07T14:09:47.0104663Z     from assimulo.problem import Implicit_Problem
2020-10-07T14:09:47.0105122Z     from assimulo.problem import Explicit_Problem
2020-10-07T14:09:47.0105578Z     from assimulo.problem cimport cExplicit_Problem
2020-10-07T14:09:47.0105965Z    ^
2020-10-07T14:09:47.0106639Z ------------------------------------------------------------
2020-10-07T14:09:47.0107040Z 
2020-10-07T14:09:47.0107828Z src/pyfmi/simulation/assimulo_interface.pxd:35:4: 'assimulo/problem/cExplicit_Problem.pxd' not found
2020-10-07T14:09:47.0110309Z 
2020-10-07T14:09:47.0110823Z Error compiling Cython file:
2020-10-07T14:09:47.0111692Z ------------------------------------------------------------
2020-10-07T14:09:47.0112134Z ...
2020-10-07T14:09:47.0112434Z         pass
2020-10-07T14:09:47.0112806Z     class Explicit_Problem:
2020-10-07T14:09:47.0113185Z         pass
2020-10-07T14:09:47.0113448Z 
2020-10-07T14:09:47.0113685Z 
2020-10-07T14:09:47.0114079Z cdef class FMIODE2(cExplicit_Problem):
2020-10-07T14:09:47.0114484Z                   ^
2020-10-07T14:09:47.0115173Z ------------------------------------------------------------
2020-10-07T14:09:47.0115560Z 
2020-10-07T14:09:47.0116341Z src/pyfmi/simulation/assimulo_interface.pxd:44:19: First base of 'FMIODE2' is not an extension type
2020-10-07T14:09:47.3027926Z warning: src/pyfmi/fmil_import.pxd:65:4: 'size_t' redeclared 
2020-10-07T14:09:47.3411761Z 
2020-10-07T14:09:47.3412799Z Error compiling Cython file:
2020-10-07T14:09:47.3413968Z ------------------------------------------------------------
2020-10-07T14:09:47.3414376Z ...
2020-10-07T14:09:47.3414728Z         self.export.integration_point(solver)#parameter_data=p_data)
2020-10-07T14:09:47.3415144Z         
2020-10-07T14:09:47.3415727Z         self.timings["handle_result"] += timer() - time_start
2020-10-07T14:09:47.3416070Z 
2020-10-07T14:09:47.3416293Z 
2020-10-07T14:09:47.3416603Z cdef class FMIODE2(cExplicit_Problem):
2020-10-07T14:09:47.3416957Z                   ^
2020-10-07T14:09:47.3417551Z ------------------------------------------------------------
2020-10-07T14:09:47.3417879Z 
2020-10-07T14:09:47.3418566Z src/pyfmi/simulation/assimulo_interface.pyx:567:19: First base of 'FMIODE2' is not an extension type
2020-10-07T14:09:47.9845310Z Traceback (most recent call last):
2020-10-07T14:09:47.9846381Z   File "setup.py", line 280, in <module>
2020-10-07T14:09:47.9846833Z     ext_list = check_extensions()
2020-10-07T14:09:47.9847288Z   File "setup.py", line 241, in check_extensions
2020-10-07T14:09:47.9847882Z     ext_list += cythonize(["src"+O.path.sep+"pyfmi"+O.path.sep+"simulation"+O.path.sep+"assimulo_interface.pyx"], 
2020-10-07T14:09:47.9850212Z   File "/home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
2020-10-07T14:09:47.9851321Z     cythonize_one(*args)
2020-10-07T14:09:47.9852928Z   File "/home/conda/feedstock_root/build_artifacts/pyfmi_1602079598983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
2020-10-07T14:09:47.9854034Z     raise CompileError(None, pyx_file)
2020-10-07T14:09:47.9854582Z Cython.Compiler.Errors.CompileError: src/pyfmi/simulation/assimulo_interface.pyx
```

**Comment by chria** [comment]
Hi,

This bool is more intended for a runtime check (once PyFMI is installed somewhere). When building now with the new updates, Assimulo is always required at the build phase.
