### ISSUE TITLE
Error in load_fmu function

### ISSUE THREAD

**Issue by bressanmarcos** [modelon-community/PyFMI#61]
Hi, when loading an example, I'm getting the following error.
```
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyfmi import load_fmu
>>> 
>>> model = load_fmu('Resistor.fmu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyfmi/fmi.pyx", line 8342, in pyfmi.fmi.load_fmu
  File "src/pyfmi/fmi.pyx", line 6701, in pyfmi.fmi.FMUModelCS2.__init__
  File "src/pyfmi/fmi.pyx", line 3930, in pyfmi.fmi.FMUModelBase2.__init__
pyfmi.fmi.FMUException: Error loading the binary. The FMU contains no binary for this platform.
```
Do you have any idea of what it could be?

**Comment by p3jawors** [comment]
I'm having the same problem trying to run the `fmu_with_input_function.run_demo()` function. I found [this stackoverflow post](https://stackoverflow.com/questions/51265302/pyfmi-modelica-the-fmu-contains-no-binary-for-this-platform) from 2018. Has there been any update on this?
